version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  target-branch: next
  labels:
  - dependencies
  allow:
  - dependency-type: direct
  ignore:
  - dependency-name: "@commitlint/cli"
    versions:
    - "> 8.3.5"
  - dependency-name: husky
    versions:
    - ">= 5.a, < 6"
  - dependency-name: semantic-release
    versions:
    - ">= 16.a, < 17"
  - dependency-name: "@types/node"
    versions:
    - ">= 13.a, < 14"
  - dependency-name: "@types/node"
    versions:
    - ">= 14.a, < 15"
  - dependency-name: "@types/node"
    versions:
    - 12.20.8
    - 15.0.0
  - dependency-name: caniuse-lite
    versions:
    - 1.0.30001218
  - dependency-name: mockdate
    versions:
    - 3.0.4
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  commit-message:
    prefix: chore
    include: scope
