on:
  push:
    branches:
      - release
      - next

name: Publish

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
        with:
          main-branch-name: 'next'
      - uses: pnpm/action-setup@v2.2.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm nx affected:lint
      - run: pnpm nx affected:test
      - run: pnpm nx run-many --target=build --all
      - name: Modify Workspace File
        run: sed -e "s|'packages\/|'dist/|" pnpm-workspace.yaml > pnpm-new.yaml && mv pnpm-new.yaml pnpm-workspace.yaml
      - name: Enter prerelease mode
        if: github.ref == 'refs/heads/next'
        run: pnpx changeset pre enter next
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish with changesets
        uses: changesets/action@v1
        with:
          version: pnpx changeset version
          publish: pnpx changeset publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Exit prerelease mode
        if: github.ref == 'refs/heads/next'
        run: pnpx changeset pre exit
